/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppearanceSettings: typeof import('./src/components/AppearanceSettings.vue')['default']
    CourseCard: typeof import('./src/components/CourseCard.vue')['default']
    CrudPage: typeof import('./src/components/CrudPage.vue')['default']
    CrudTable: typeof import('./src/components/CrudTable.vue')['default']
    ElAlert: typeof import('element-plus/es/components/alert/index')['ElAlert']
    ElButton: typeof import('element-plus/es/components/button/index')['ElButton']
    ElCard: typeof import('element-plus/es/components/card/index')['ElCard']
    ElColorPicker: typeof import('element-plus/es/components/color-picker/index')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es/components/config-provider/index')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es/components/date-picker/index')['ElDatePicker']
    ElDialog: typeof import('element-plus/es/components/dialog/index')['ElDialog']
    ElDrawer: typeof import('element-plus/es/components/drawer/index')['ElDrawer']
    ElDropdown: typeof import('element-plus/es/components/dropdown/index')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es/components/dropdown/index')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es/components/dropdown/index')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es/components/empty/index')['ElEmpty']
    ElForm: typeof import('element-plus/es/components/form/index')['ElForm']
    ElFormItem: typeof import('element-plus/es/components/form/index')['ElFormItem']
    ElIcon: typeof import('element-plus/es/components/icon/index')['ElIcon']
    ElImage: typeof import('element-plus/es/components/image/index')['ElImage']
    ElInput: typeof import('element-plus/es/components/input/index')['ElInput']
    ElInputNumber: typeof import('element-plus/es/components/input-number/index')['ElInputNumber']
    ElOption: typeof import('element-plus/es/components/select/index')['ElOption']
    ElPagination: typeof import('element-plus/es/components/pagination/index')['ElPagination']
    ElPopover: typeof import('element-plus/es/components/popover/index')['ElPopover']
    ElResult: typeof import('element-plus/es/components/result/index')['ElResult']
    ElSelect: typeof import('element-plus/es/components/select/index')['ElSelect']
    ElSkeleton: typeof import('element-plus/es/components/skeleton/index')['ElSkeleton']
    ElTable: typeof import('element-plus/es/components/table/index')['ElTable']
    ElTableColumn: typeof import('element-plus/es/components/table/index')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es/components/tabs/index')['ElTabPane']
    ElTabs: typeof import('element-plus/es/components/tabs/index')['ElTabs']
    ElTag: typeof import('element-plus/es/components/tag/index')['ElTag']
    ElTree: typeof import('element-plus/es/components/tree/index')['ElTree']
    ElUpload: typeof import('element-plus/es/components/upload/index')['ElUpload']
    ExamCountdownTag: typeof import('./src/components/ExamCountdownTag.vue')['default']
    ProgressRing: typeof import('./src/components/ProgressRing.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaForm: typeof import('./src/components/SchemaForm.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es/components/loading/index')['ElLoadingDirective']
  }
}
